language: node_js
node_js:
- 8.5.0
notification:
  email: false
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: cgHn5G/Hw0Vd92wU4VmrHqGalAEwqC8/XyD18Fp7Wxx3aMWJnPph3L16MixdXCjq2YvO2WVNd8EuQ2emq43OAS9aek9ovdrcYwqQT0yPakzKygL+TYJvVC91r0ZlCzm49MnjNNoWFiDq76cneeIu7Wegbrrz6zHWduo/txKD495aRWpxHHusJKNxmGBN5Ns0kiiuFskb9wOmTgC5VulKdYGEziEDXI/Ru5dGZCsA4WetbvRuG9HLQP9qZrlWm4Bwtq4vHAecKC/jIhcLFy5OF608fB25fySRg81+w4jYzRSBEu1haHBy2YI35pn99J/spT0rf3ImqvRuU9O5lhaAM59fMKvjdPxMmlZZ8DNkiRZ86QkUVp6qO59mh1AI3FclNiM0oQVks9i7AaMTW5F9T1sVp4xJOPQBcRCGaVTbqHYKky1/SP8eeRrgOoz/tK35vn9gbj23vv5LtZo09OWwxU/LKwbq2nX1nJALJVKVpB0W456nbbOYuB3DHj6Aa4ou8Zioihv+Qv81Gco4HpCBbSD91zryYDzJbYLB0m9nH6fg2dAsYMDYBDktNySjowgTfJyG94WmJ2OqvwREBWGOpgTCX1DmLOIh2ejeRaIYM5jddZt3UBRbMAek9tOC03Y4NHTlI5Q3X8mtoeW1muowROL4W9eRgfIGHVW/PkG+nCM=
  app: frontmenpool
  on:
    all_branches: true
